sonar.projectKey=Jhonnathan93_integrating-project-1
sonar.organization=jhonnathan93
sonar.projectName=BookNexus
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.exclusions=**/migrations/**,**/tests/**,static/vendor/**,static/img/**
sonar.python.version=3.14
sonar.python.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=**/tests/**,**/migrations/**
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
