sonar.projectKey=Jhonnathan93_integrating-project-1
sonar.organization=jhonnathan93
sonar.projectName=BookNexus
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.exclusions=**/migrations/**,static/vendor/**,static/img/**
sonar.python.version=3.14
sonar.coverage.exclusions=**/tests.py,**/migrations/**
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
