"""
Django settings for BookNexus project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"

load_dotenv(BASE_DIR / ".env")

GOOGLE_BOOKS_API_KEY = os.environ.get(
    "GOOGLE_BOOKS_API_KEY", os.environ.get("googlebooks_api_key", "")
)
OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", os.environ.get("openAI_api_key", ""))
GROQ_API_KEY = os.environ.get("GROQ_API_KEY", "")
LLM_PROVIDER = os.environ.get("LLM_PROVIDER", "groq").lower()
GROQ_MODEL = os.environ.get("GROQ_MODEL", "llama-3.3-70b-versatile")
OPENAI_MODEL = os.environ.get("OPENAI_MODEL", "gpt-5.4-mini")
NEWSLETTER_SENDER_EMAIL = os.environ.get(
    "NEWSLETTER_SENDER_EMAIL", os.environ.get("sender_email", "")
)
NEWSLETTER_SENDER_PASSWORD = os.environ.get(
    "NEWSLETTER_SENDER_PASSWORD", os.environ.get("password", "")
)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY", os.environ.get("SECRET_KEY", "unsafe-development-secret-key")
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "false").strip().lower() == "true"


def get_environment_list(*variable_names: str) -> list[str]:
    """Return comma-separated values from environment variables without whitespace."""
    values: list[str] = []
    for variable_name in variable_names:
        values.extend(
            value.strip()
            for value in os.environ.get(variable_name, "").split(",")
            if value.strip()
        )
    return values


VERCEL_HOST_SUFFIX = ".vercel.app"

ALLOWED_HOSTS = (
    get_environment_list("DJANGO_ALLOWED_HOSTS", "ALLOWED_HOSTS") if not DEBUG else []
)
if not DEBUG and VERCEL_HOST_SUFFIX not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(VERCEL_HOST_SUFFIX)

CSRF_TRUSTED_ORIGINS = get_environment_list("CSRF_TRUSTED_ORIGINS")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "accounts",
    "book",
    "readinglists",
    "newsletter",
    "analytics",
    "reports",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "BookNexus.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "BookNexus/templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "BookNexus.wsgi.application"


# Database
# A local SQLite database keeps development simple. Deployments provide a
# PostgreSQL connection string through DATABASE_URL (for example, Supabase).
DATABASE_URL = os.environ.get("DATABASE_URL")

if DATABASE_URL:
    database_config = dj_database_url.parse(
        DATABASE_URL,
        conn_max_age=0,
        conn_health_checks=True,
    )
    # Supabase's transaction pooler does not support prepared statements.
    database_config.setdefault("OPTIONS", {})["prepare_threshold"] = None
    DATABASES = {"default": database_config}
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": str(BASE_DIR / "db.sqlite3"),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "America/Bogota"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "/static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
