# Generated by Django 4.2.4 on 2023-11-04 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0005_alter_history_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='userInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateField()),
                ('preferences', models.TextField(max_length=300)),
                ('profile_picture', models.ImageField(upload_to='accounts/profile_pics/')),
                ('points', models.PositiveSmallIntegerField()),
                ('disliked_books', models.ManyToManyField(blank=True, related_name='disliked_by', to='book.book')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
