# Generated by Django 4.2.4 on 2023-11-20 02:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_userinformation_disliked_books"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinformation",
            name="birthdate",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="userinformation",
            name="points",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
