# Generated by Django 4.2.4 on 2023-10-15 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_delete_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("password", models.CharField(max_length=30)),
                ("email", models.CharField(max_length=40)),
                ("age", models.SmallIntegerField(blank=True, null=True)),
                ("gender", models.BooleanField(blank=True, null=True)),
                ("points", models.IntegerField(blank=True, null=True)),
                (
                    "profile_pic",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
    ]
