<<<<<<< HEAD
# Generated by Django 4.2.1 on 2023-10-13 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
=======
# Generated by Django 4.2.4 on 2023-10-15 00:29

from django.db import migrations, models
>>>>>>> 9966cb7679b911f1d7cad73a4d9665616d7ca04a


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_delete_userprofile'),
=======
        ("accounts", "0003_delete_userprofile"),
>>>>>>> 9966cb7679b911f1d7cad73a4d9665616d7ca04a
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=45, unique=True)),
                ('birthdate', models.DateField()),
                ('preferences', models.TextField(max_length=300)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
=======
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("password", models.CharField(max_length=30)),
                ("email", models.CharField(max_length=40)),
                ("age", models.SmallIntegerField(blank=True, null=True)),
                ("gender", models.BooleanField(blank=True, null=True)),
                ("points", models.IntegerField(blank=True, null=True)),
                (
                    "profile_pic",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
>>>>>>> 9966cb7679b911f1d7cad73a4d9665616d7ca04a
            ],
        ),
    ]
