# Generated by Django 4.2.4 on 2023-10-15 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="User", new_name="Reader",),
    ]
