# Generated by Django 4.2.4 on 2023-10-15 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_rename_user_reader"),
    ]

    operations = [
        migrations.RenameModel(old_name="Reader", new_name="Readers",),
    ]
