# Generated by Django 4.2.4 on 2023-09-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readinglists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='readinglist',
            name='cover',
            field=models.ImageField(default='default_cover.jpg', upload_to='readinglists/covers/'),
        ),
        migrations.AddField(
            model_name='readinglist',
            name='description',
            field=models.CharField(default='abc', max_length=250),
        ),
    ]
