# Generated by Django 4.2.4 on 2023-10-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readinglists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='readinglist',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
