# Generated by Django 4.2.4 on 2023-09-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readinglists', '0002_readinglist_cover_readinglist_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readinglist',
            name='cover',
            field=models.ImageField(upload_to='readinglists/covers/'),
        ),
        migrations.AlterField(
            model_name='readinglist',
            name='description',
            field=models.CharField(max_length=250),
        ),
    ]
