# Generated by Django 4.2.4 on 2023-09-10 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('readinglists', '0003_alter_readinglist_cover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='readinglist',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
