# Generated by Django 4.2.4 on 2023-11-04 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readinglists', '0004_alter_readinglist_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readinglist',
            name='cover',
            field=models.ImageField(blank=True, default='readinglist/default_book.png', null=True, upload_to='readinglists/covers/'),
        ),
    ]
