# Generated by Django 4.2.1 on 2023-09-14 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('readinglists', '0005_alter_readinglist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readinglist',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
