# Generated by Django 4.2.4 on 2023-10-17 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reader",
            name="id",
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
