# Generated by Django 4.2.4 on 2023-08-17 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Reader',
        ),
    ]
