# Generated by Django 4.2.4 on 2023-10-15 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0006_alter_book_cover"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=40)),
                ("password", models.CharField(max_length=30)),
                (
                    "email",
                    models.EmailField(default="example@example.com", max_length=254),
                ),
                ("age", models.SmallIntegerField()),
                ("gender", models.CharField(max_length=40)),
                ("points", models.IntegerField()),
                ("profile_pic", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(model_name="reader", name="name",),
        migrations.RemoveField(model_name="reader", name="profile_pic",),
    ]
