# Generated by Django 4.2.4 on 2023-10-15 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0007_user_remove_reader_name_remove_reader_profile_pic"),
    ]

    operations = [
        migrations.DeleteModel(name="User",),
        migrations.AddField(
            model_name="reader", name="age", field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="reader",
            name="email",
            field=models.EmailField(default="example@example.com", max_length=50),
        ),
        migrations.AddField(
            model_name="reader",
            name="gender",
            field=models.CharField(default="Otro", max_length=40),
        ),
        migrations.AddField(
            model_name="reader",
            name="name",
            field=models.CharField(default="", max_length=40),
        ),
        migrations.AddField(
            model_name="reader",
            name="password",
            field=models.CharField(default="j7531594862", max_length=30),
        ),
        migrations.AddField(
            model_name="reader", name="points", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="reader",
            name="profile_pic",
            field=models.CharField(
                default="https://i.pinimg.com/280x280_RS/42/03/a5/4203a57a78f6f1b1cc8ce5750f614656.jpg",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="reader",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
