# Generated by Django 4.2.4 on 2023-11-07 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0008_book_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book", old_name="date", new_name="dateAdded",
        ),
    ]
